### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MajorSkyblue** [palechip/HudPixel#106]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 18/08/15 02:22
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: 8196
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(SourceFile:58)
	at net.minecraft.block.BlockStairs.func_176306_h(SourceFile:243)
	at net.minecraft.block.BlockStairs.func_176221_a(SourceFile:607)
	at net.minecraft.block.Block.isSideSolid(Block.java:1048)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:198)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:42)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:891)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:866)
	at ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:759)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:420)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:184)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:257)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:112)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:61)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:50)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:250)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(SourceFile:58)
	at net.minecraft.block.BlockStairs.func_176306_h(SourceFile:243)
	at net.minecraft.block.BlockStairs.func_176221_a(SourceFile:607)
	at net.minecraft.block.Block.isSideSolid(Block.java:1048)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:198)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:42)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:891)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:866)
	at ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:759)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:420)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:184)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:257)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:112)

-- Block model being tesselated --
Details:
	Block: minecraft:stained_glass[color=yellow]
	Block location: World: (-2609,45,839), Chunk: (at 15,2,7 in -164,52; contains blocks -2624,0,832 to -2609,255,847), Region: (-6,1; contains chunks -192,32 to -161,63, blocks -3072,0,512 to -2561,255,1023)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:61)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:50)

-- Block being tesselated --
Details:
	Block type: ID #95 (tile.stainedGlass // net.minecraft.block.BlockStainedGlass)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-2609,45,839), Chunk: (at 15,2,7 in -164,52; contains blocks -2624,0,832 to -2609,255,847), Region: (-6,1; contains chunks -192,32 to -161,63, blocks -3072,0,512 to -2561,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)

-- Affected level --
Details:
	Level name: MpServer
	All players: 35 total; [EntityPlayerSP['MajorSkyblue'/519332, l='MpServer', x=-2557.90, y=55.52, z=751.70], EntityOtherPlayerMP[''/-1, l='MpServer', x=-2520.50, y=54.00, z=742.50], EntityOtherPlayerMP[''/-2, l='MpServer', x=-2520.50, y=54.00, z=746.50], EntityOtherPlayerMP[''/-3, l='MpServer', x=-2520.50, y=54.00, z=748.50], EntityOtherPlayerMP[''/-4, l='MpServer', x=-2520.50, y=54.00, z=740.50], EntityOtherPlayerMP['TheBarcodePlayer'/507236, l='MpServer', x=-2553.59, y=50.00, z=745.00], EntityOtherPlayerMP['bigbadbull25'/516168, l='MpServer', x=-2551.03, y=50.00, z=744.50], EntityOtherPlayerMP['shsigrid28'/515685, l='MpServer', x=-2552.25, y=50.00, z=743.50], EntityOtherPlayerMP['CYB3RCrazy_Jason'/515692, l='MpServer', x=-2551.66, y=50.00, z=744.16], EntityOtherPlayerMP['Lilbobo'/513771, l='MpServer', x=-2545.84, y=49.00, z=744.66], EntityOtherPlayerMP['MrAndrewxK'/508995, l='MpServer', x=-2553.34, y=50.00, z=745.56], EntityOtherPlayerMP['Flameaton5'/518387, l='MpServer', x=-2539.78, y=50.00, z=739.94], EntityOtherPlayerMP['_NILLEKE_'/513592, l='MpServer', x=-2532.31, y=50.00, z=737.53], EntityOtherPlayerMP['DeliveryMan'/242, l='MpServer', x=-2531.50, y=50.00, z=767.50], EntityOtherPlayerMP['ultromis'/519282, l='MpServer', x=-2537.45, y=50.00, z=752.13], EntityOtherPlayerMP['Ravini_Mephisto'/519289, l='MpServer', x=-2536.66, y=50.00, z=760.06], EntityOtherPlayerMP['JJCachen'/519296, l='MpServer', x=-2539.09, y=50.00, z=766.69], EntityOtherPlayerMP['Skittle_M0D'/506036, l='MpServer', x=-2546.31, y=49.63, z=729.88], EntityOtherPlayerMP['Karasume'/518452, l='MpServer', x=-2542.00, y=50.00, z=724.94], EntityOtherPlayerMP['DeliveryMan'/234, l='MpServer', x=-2530.50, y=50.00, z=721.50], EntityOtherPlayerMP['SparrowMech'/518778, l='MpServer', x=-2536.72, y=52.00, z=720.38], EntityOtherPlayerMP['MattBeau'/519240, l='MpServer', x=-2547.16, y=51.00, z=771.41], EntityOtherPlayerMP['Knights17'/518800, l='MpServer', x=-2532.03, y=50.00, z=721.84], EntityOtherPlayerMP['minecraftpro7281'/519146, l='MpServer', x=-2619.49, y=53.00, z=757.75], EntityOtherPlayerMP['MagmaMax500'/519052, l='MpServer', x=-2630.44, y=50.50, z=742.27], EntityOtherPlayerMP['JPS111'/519339, l='MpServer', x=-2552.28, y=50.00, z=743.75], EntityOtherPlayerMP['Annihilator8000'/519642, l='MpServer', x=-2553.88, y=50.50, z=745.75], EntityOtherPlayerMP['BlazeHunter550'/519671, l='MpServer', x=-2550.50, y=50.00, z=747.06], EntityOtherPlayerMP['hjkwon711'/519692, l='MpServer', x=-2538.44, y=50.02, z=765.78], EntityOtherPlayerMP['Erudesuto'/519706, l='MpServer', x=-2551.31, y=52.00, z=745.69], EntityOtherPlayerMP['kaycoolgirl1'/519713, l='MpServer', x=-2538.70, y=50.00, z=758.08], EntityOtherPlayerMP['kiwikillerjj'/519720, l='MpServer', x=-2539.66, y=50.00, z=764.00], EntityOtherPlayerMP['barrysfish'/519727, l='MpServer', x=-2553.97, y=52.00, z=743.75], EntityOtherPlayerMP['JacobC1010'/519741, l='MpServer', x=-2548.77, y=49.00, z=743.02], EntityOtherPlayerMP['kickass7979'/519664, l='MpServer', x=-2533.00, y=50.00, z=726.72]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -2553.00,52.00,744.00 - World: (-2553,52,744), Chunk: (at 7,3,8 in -160,46; contains blocks -2560,0,736 to -2545,255,751), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Level time: 311699530 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: ~~ERROR~~ ConcurrentModificationException: null
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:407)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2503)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3253069280 bytes (3102 MB) / 4146069504 bytes (3954 MB) up to 4146069504 bytes (3954 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1502 Optifine OptiFine_1.8_HD_U_D5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1502.jar) 
	UCHIJA	Forge{11.14.3.1502} [Minecraft Forge] (forge-1.8-11.14.3.1502.jar) 
	UCHIJA	hudpixel{2.5.0} [HudPixel Reloaded] (MC-1.8-HudPixelReloaded-2.5.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.8-Forge11.14.3.1502
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Main Faithful 32x32 - Reduced Fire.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by MajorSkyblue** [comment]
I've had this crash 3 times since installing HudPixel and Forge about an hour ago. It only seems to happen in the Warlords lobby as I haven't got it in any Warlords games or any other games yet.

**Comment by palechip** [comment]
This crash report has nothing to do with HudPixel. For me it looks like Optifine is to blame.
The stacktrace suggests that it is related with the connected texture feature. Please try disabling connected textures.
